/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PrakrutiType = IDL.Variant({
  'Vata' : IDL.Null,
  'Pitta' : IDL.Null,
  'Kapha' : IDL.Null,
});
export const FacialConditions = IDL.Record({
  'faceShape' : IDL.Text,
  'puffiness' : IDL.Text,
  'skinTone' : IDL.Text,
  'darkCircles' : IDL.Text,
});
export const DoshaScores = IDL.Record({
  'vata' : IDL.Float64,
  'pitta' : IDL.Float64,
  'kapha' : IDL.Float64,
});
export const AnalysisResult = IDL.Record({
  'id' : IDL.Nat,
  'prakruti' : PrakrutiType,
  'questAnswers' : IDL.Vec(IDL.Text),
  'facialConditions' : FacialConditions,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
  'doshaScores' : DoshaScores,
});

export const idlService = IDL.Service({
  'getAnalysisById' : IDL.Func([IDL.Nat], [IDL.Opt(AnalysisResult)], ['query']),
  'getAnalysisCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLatestAnalysis' : IDL.Func([], [IDL.Opt(AnalysisResult)], ['query']),
  'storeAnalysis' : IDL.Func(
      [
        PrakrutiType,
        DoshaScores,
        IDL.Float64,
        FacialConditions,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PrakrutiType = IDL.Variant({
    'Vata' : IDL.Null,
    'Pitta' : IDL.Null,
    'Kapha' : IDL.Null,
  });
  const FacialConditions = IDL.Record({
    'faceShape' : IDL.Text,
    'puffiness' : IDL.Text,
    'skinTone' : IDL.Text,
    'darkCircles' : IDL.Text,
  });
  const DoshaScores = IDL.Record({
    'vata' : IDL.Float64,
    'pitta' : IDL.Float64,
    'kapha' : IDL.Float64,
  });
  const AnalysisResult = IDL.Record({
    'id' : IDL.Nat,
    'prakruti' : PrakrutiType,
    'questAnswers' : IDL.Vec(IDL.Text),
    'facialConditions' : FacialConditions,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
    'doshaScores' : DoshaScores,
  });
  
  return IDL.Service({
    'getAnalysisById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AnalysisResult)],
        ['query'],
      ),
    'getAnalysisCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLatestAnalysis' : IDL.Func([], [IDL.Opt(AnalysisResult)], ['query']),
    'storeAnalysis' : IDL.Func(
        [
          PrakrutiType,
          DoshaScores,
          IDL.Float64,
          FacialConditions,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };