/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'id' : bigint,
  'prakruti' : PrakrutiType,
  'questAnswers' : Array<string>,
  'facialConditions' : FacialConditions,
  'timestamp' : bigint,
  'confidence' : number,
  'doshaScores' : DoshaScores,
}
export interface DoshaScores {
  'vata' : number,
  'pitta' : number,
  'kapha' : number,
}
export interface FacialConditions {
  'faceShape' : string,
  'puffiness' : string,
  'skinTone' : string,
  'darkCircles' : string,
}
export type PrakrutiType = { 'Vata' : null } |
  { 'Pitta' : null } |
  { 'Kapha' : null };
export interface _SERVICE {
  'getAnalysisById' : ActorMethod<[bigint], [] | [AnalysisResult]>,
  'getAnalysisCount' : ActorMethod<[], bigint>,
  'getLatestAnalysis' : ActorMethod<[], [] | [AnalysisResult]>,
  'storeAnalysis' : ActorMethod<
    [PrakrutiType, DoshaScores, number, FacialConditions, Array<string>],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];